services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: planning_db
      MYSQL_USER: planning_user
      MYSQL_PASSWORD: planning_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: planning_db
      DATABASE_USERNAME: planning_user
      DATABASE_PASSWORD: planning_password
      NODE_ENV: development
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/opt/app
      - strapi_data:/opt/app/public/uploads
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_STRAPI_URL: https://strapi.clavier.dev
      VITE_STRAPI_API_TOKEN: ${STRAPI_API_TOKEN:-a18990837aaec95b8a205895a214502e3e433b113d828102600bb0e46f629f84d1efd5296734655ecceea3cee5fef27bac4015e076935822070fdddf2a2a6a48d6faa8095255c524abdf3285659d0a3093aba46d803d4457cdf19108bf56a118e6d369dd976e06ce3905d2293c689ba71c203df20afe2bdcd6429651b333bc47}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mysql_data:
  strapi_data:
